### ISSUE TITLE
Calculation and fixation

### ISSUE THREAD

**Issue by freedomlizhigang** [s-yadav/patternLock#10]
// newX = (posObj.i - 1) * (2 * margin + 2 * radius) + 2 * margin + radius,
// newY = (posObj.j - 1) * (2 * margin + 2 * radius) + 2 * margin + radius;
// Instead of calculating the position of the current element, it can be arranged into any shape.
newX = elm.position().left,
newY = elm.position().top;

**Comment by s-yadav** [comment]
Is calculating causing any issue??

**Comment by freedomlizhigang** [comment]
Thank you
Your plugin to calculate the mark point distribution can only be square and in some cases may use other shapes, like a triangle, so I hope line to connect the beginning point can follow the mark point distribution, personal needs, the main source of revision submitted, first submitted do not know where to put so here, sorry
My English is not good, the software translation comes!
