### ISSUE TITLE
How do I complete full circuit?

### ISSUE THREAD

**Issue by nirajmchauhan** [s-yadav/patternLock#11]
I want to know how can I complete the entire circuit, like if I want an entire box then how do I achieve, please find attach screenshot:
<img width="482" alt="screen shot 2016-01-18 at 12 39 21 pm" src="https://cloud.githubusercontent.com/assets/1540451/12385298/a5359320-bde0-11e5-998c-c37c8dcfe2f0.png">

So now the entire square is not formed, the plugin is restricting me to do that, I know in android also it cannot happen, but how do I achieve this?

**Comment by khangaikh** [comment]
I have same problem. I would like go over dotes again

**Comment by s-yadav** [comment]
@nirajmchauhan @khangaikh It does not allow to go over same dots. This is similar to how android patternlock behaves. But if you want it you can comment if condition check in line no 121 

```js
if (patternAry.indexOf(pattId) == -1) {
```

**Comment by khangaikh** [comment]
Thanks @s-yadav
