### ISSUE TITLE
Separate patterns in one grid

### ISSUE THREAD

**Issue by khangaikh** [s-yadav/patternLock#14]
I am trying to make lock that not necessary continuously connect dots. I want to also draw my first pattern and draw another pattern in for example 5x5 grid separately. Please guide me through your code?

**Comment by khangaikh** [comment]
any ideas @s-yadav

**Comment by s-yadav** [comment]
This is not an intended behaviour for a pattern lock, but if you need it, add following method in patternLock's prototype (inside patternLock.js, may be after reset method)

```js
        resetPointer : function(){
            var iObj = objectHolder[this.token];
            
            iObj.patternAry = iObj.patternAry || [];
            //remove last Obj
            iObj.lastPosObj = null;
        }
```

and replace line 96
```js
obj.reset();
 //to
obj.resetPointer();
```

As lock willl not reset by itself when user try to draw a new pattern, so you should give a button to reset patternLock in cick of which call .reset() method.

**Comment by khangaikh** [comment]
Thanks @s-yadav
