### ISSUE TITLE
Issue in drawing from Right to Left  or Bottom to top

### ISSUE THREAD

**Issue by sanjeevrajput01** [s-yadav/patternLock#15]
Issue in drawing from Right to LEFT or Bottom to top. Library does not covers all points. it skipes some points in reverse directions.

![image](https://cloud.githubusercontent.com/assets/19407698/15321087/f5d32160-1c51-11e6-8322-725fcc73a63f.png)

**Comment by sanjeevrajput01** [comment]
I have done some changes in this library.
Please change in while loop. and try this.


while (((iDiff == 0 && jDiff > 1) || (jDiff == 0 && iDiff > 1) || (jDiff == iDiff && jDiff > 1)) && !(jp == posObj.j && ip == posObj.i)) { 
                            var ipTemp = posObj.i - ip;
                            var jpTemp = posObj.j - jp;
                            if(ipTemp < 0){
                                ip = iDiff ? Math.max(posObj.i, ip) - 1 : ip;
                            }else{
                                ip = iDiff ? Math.min(posObj.i, ip) + 1 : ip;
                            }
                            if(jpTemp < 0){
                                jp = jDiff ? Math.max(posObj.j, jp) - 1 : jp;
                            }else{
                                jp = jDiff ? Math.min(posObj.j, jp) + 1 : jp;
                            }
                            iDiff = Math.abs(posObj.i - ip);
                            jDiff = Math.abs(posObj.j - jp);

                            var nextIdx = (jp - 1) * iObj.option.matrix[1] + ip,
                                nextPattId = iObj.mapperFunc(nextIdx) || nextIdx;

                            if (patternAry.indexOf(nextPattId) == -1) {
                                $(li[nextIdx - 1]).addClass('hovered');
                                //push pattern on array
                                patternAry.push(nextPattId);
                            }
                        }``

**Comment by s-yadav** [comment]
@sanjeevrajput01 Thanks for pointing it out. Fixed in version 1.0.1
