### ISSUE TITLE
How to create complex pattern

### ISSUE THREAD

**Issue by ebencosoft** [s-yadav/patternLock#16]
Hi,
Great job well done......can you come up with update so that some one can create complex pattern because now the pattern predictable in case you are using as authentication some one easily grab the pattern and use it.....so update that can you generate 10-15 number from a pattern using matrix 3,3.....like to draw on particular line twice......for example.....1457894773......

**Comment by s-yadav** [comment]
@ebencosoft  Added allowRepeat option in latest release, this will allow to go over same dots again.
