### ISSUE TITLE
Illegal patterns allowed

### ISSUE THREAD

**Issue by marteloge** [s-yadav/patternLock#3]
Is it possible to add a functionality to check if pattern is valid? 
At the moment it is possible to add the following sequence "1-3-2" by drawing a line outside the box.
This should not be allowed.

**Comment by s-yadav** [comment]
Thanks, you are right 1-3-2 sequence is not a valid, it should put 2 automatically in sequence, if any one directly goes from 1 to 3.
I will fix this as soon as possible. For now if you need to do manual check, you can use onDraw callback and using error method you can show user that sequence is invalid. For help you can refer http://ignitersworld.com/lab/patternLock.html#callback .

**Comment by marteloge** [comment]
Thank you! 
This library saved me hours on my masterproject. You have done a great job!

Let me know when you have fixed this issue :)

**Comment by marteloge** [comment]
My friend just made a quick fix until you have released a new version (https://gist.github.com/hawkaa/d97ce63f8a0e79aec66c). 
It checks if the pattern is a valid pattern (not the length). This code detects if nodes that should be in the pattern list are skipped (feks "1-3-6-9", where 2 is skipped and should be in the list).

This is nice to have because sometimes when you write a pattern, it sometimes misses some nodes.
Sometimes when I create a pattern, some of the selected nodes does not get hovered nor added to the pattern list.

**Comment by s-yadav** [comment]
New release 0.4.1 is released with issue been fixed, so if you go directly from 1 to 3 it will select 2 in middle automatically. This will be on all horizontal, diagonal, vertical case. You can check demo link ignitersworld.com/lab/patternLock.html to see how it behaves.

**Comment by nejdetckenobi** [comment]
Hi, here is some strange behaviour about this issue.
![bugss](https://cloud.githubusercontent.com/assets/4905664/16726784/0aa45e60-472c-11e6-93ea-5bdbc18f5cf3.png)

Is it natural or?

**Comment by s-yadav** [comment]
@nejdetckenobi  Fixed in v1.0.1 .
