### ISSUE TITLE
lock.option('patternVisible', false) is not work

### ISSUE THREAD

**Issue by whitewizard007** [s-yadav/patternLock#4]
Hi,
I try to change the patternVisible when user click a checkbox. This is my source code:

    $scope.lock1 = new PatternLock('#lock1', { patternVisible: false });
    $scope.togglePatternVisible = function(){
        console.log("Before:"+this.isPatternVisible + "||"+$scope.lock1.option('patternVisible'));
        if(this.isPatternVisible){
            $scope.lock1.option('patternVisible', true);
        }else{
            $scope.lock1.option('patternVisible', false);
        }
        console.log("After:"+this.isPatternVisible + "||"+$scope.lock1.option('patternVisible'));
    };

At first, my checkbox is unchecked and patternVisible is false.
After user click the checkbox, the togglePatternVisible function is run.
Below is javascript console log that i tried to toggle the checkbox.

Before:true||false
After:true||true
Before:false||true
After:false||true

Please help me to fix this issue. Thanks in advance

Aek.

**Comment by s-yadav** [comment]
Fixed. https://github.com/s-yadav/patternLock/commit/6a902c3b4ae5a5a80b97a381e0425d46c416131b
