### ISSUE TITLE
version without jquery

### ISSUE THREAD

**Issue by pochy-ja** [s-yadav/patternLock#8]
it would be possible to have a version without jquery?

In mobile systems like firefox OS, Jquery is to much for compatibility in the platform and the GAIA layer, because we need a version without jquery if would be possible.

**Comment by s-yadav** [comment]
What about zepto? Can you guys use zepto? It is light weight and patternlock must work on that too. Not tested though.

**Comment by pochy-ja** [comment]
Thanks, I submit a PR for you to do support in your library to use zepto o jquery, depend of the choice.

**Comment by JosefJezek** [comment]
http://youmightnotneedjquery.com

**Comment by jasondavis** [comment]
I was searching for a Native JS (non jQuery version) of a Pattern lock library and came across this library.  

Looking at the code, it does not look like this library even uses jQuery for very many things.

At a quick glance I saw jQuery used to:

- set some CSS properties on element
- add CSS class to element
- remove CSS class from element
- define DOM event handlers

as mentioned I only glanced over the code quickly but from the look of it it seems those are the only items jQuery is needed for.  All of these are very easy to switch out with Native JavaScript versions.

I might spend like 30 minutes and see if I can port it over to Native JS and if it works out i'll send a pull request for an optional 2nd pure JS version of the library.  I have seen many other repos that offer a jQuery and Pure JS version of a library.

**Comment by s-yadav** [comment]
Finally after a long time removed jQuery dependency on v2.0.0

**Comment by simowaer** [comment]
@s-yadav jQuery is still listed as a dependency in package.json. How can I install this without jQuery?

**Comment by s-yadav** [comment]
Or must have missed it. Will fix this
